# =============================================
# BASE DE DATOS - PostgreSQL (Render)
# Render inyecta DATABASE_URL automáticamente
# =============================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Zona horaria Peru
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
server.tomcat.timezone=America/Lima

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Servidor (Render asigna el PORT dinamicamente)
server.port=${PORT:8080}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Archivos estaticos e imagenes subidas
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# Actuator - health check para Render
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# =============================================
# CLOUDINARY
# =============================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dxatzxc4y}
cloudinary.api-key=${CLOUDINARY_API_KEY:767881232698992}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:C-s2QypnBPmi6B4rgpAxQQ8fviE}


# ── DATOS EMPRESA ──
empresa.nombre=CAR DETAILING GADIEL E.I.R.L.
empresa.ruc=20615184421
empresa.direccion=Jr. Barrio Magdalena 295, Huamanga, Ayacucho
empresa.telefono=999193213

# ── NUBEFACT (SUNAT) ──
nubefact.url=https://api.nubefact.com/api/v1/c69d017d-adea-4fe5-ab1f-cf7990bf992e
nubefact.token=2843dc87ef074cddbbf9664328e05b0da33a8c6dc861429d809f6f6492c11aa9
nubefact.modo=2
nubefact.ruc=20615184421


# Series de comprobantes
sunat.serie.boleta=BBB1
sunat.serie.factura=FFF1

logging.level.root=WARN
logging.level.com.carwash=INFO

# API RENIEC - apiperu.dev
reniec.api.url=https://apiperu.dev/api/dni/
reniec.api.token=eac607b47f1aaabddf5c3058677ded9ea03adad6aacc60d3db81d39fc72da03e

# Tamaño máximo de imagen subida
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB